version: "3.9"

services:
  back:
    container_name: shwit-graph
    build:
      context: ./back
    environment:
      HOST: db
    ports:
      - "${PORT-4000}:4000"
    volumes:
      - ./back:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - shwitter

  db:
    image: postgres:14.1-alpine
    container_name: shwit-db
    env_file:
      - ./back/.env
    # environment:
    #   POSTGRES_USER: ${DATABASE_USERNAME}
    #   POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    #   POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DB_PORT-5432}:5432"
    volumes:
      - postgres_dev:/var/lib/postgresql
    networks:
      - shwitter

  front:
    container_name: shwit-ui
    build:
      context: ./front
    ports:
      - "${FRONT_PORT-3000}:3000"
    stdin_open: true
    volumes:
      - ./front:/app
      - /app/node_modules

volumes:
  postgres_dev:

networks:
  shwitter:
    name: 'shwitter-net'
