version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    container_name: shwit-db
    env_file:
      - .env
    # environment:
    #   POSTGRES_USER: ${DATABASE_USERNAME}
    #   POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    #   POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DB_PORT-5432}:5432"
    volumes:
      - postgres_dev:/var/lib/postgresql

volumes:
  postgres_dev:

