# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build
    runs-on: ubuntu-latest
    env:
      key1: ${{secrets.PORT}}

    steps:
    # Steps represent a sequence of tasks that will be executed as part of the job
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: executing remote ssh commands using ssh key
                
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_ED25519 }}
          port: ${{ secrets.PORT }}
          script: |
            if test ! -e Projects/shwitter 
              mkdir Projects
              git clone https://github.com/m3dsh/shwitter Projects/shwitter
            end
            cd Projects/shwitter
            git fetch origin main
            git reset --hard origin/main
            docker compose -f docker-compose.prod.yml up --build -d


